language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install

env:
  global:
    - NODE_ENV=test

before_script:
  - npm run build
script:
  - npm test
after_success:
  - npm run coverage
